# Generated by Django 5.2.16 on 2026-07-22 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_employee_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_days', models.PositiveIntegerField(default=7, help_text='How many days an item stays highlighted after an employee takes it')),
                ('reset_mode', models.CharField(choices=[('fixed_time', 'Reset at a fixed time each day'), ('hours_after', 'Reset N hours after each assignment')], default='fixed_time', max_length=20)),
                ('reset_time', models.TimeField(default='00:00', help_text="Used when reset mode is 'fixed time'. The 'today' highlight clears at this time.")),
                ('reset_hours', models.PositiveIntegerField(default=20, help_text="Used when reset mode is 'hours after'. Hours after taking an item before it stops counting as 'today'.")),
                ('color_today', models.CharField(default='#dc2626', help_text='Color for items taken today (or within the reset window)', max_length=7)),
                ('color_period', models.CharField(default='#2563eb', help_text='Color for items taken within the period window', max_length=7)),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, help_text='Items at or below this stock level are flagged low on the Items/Stock tabs')),
            ],
        ),
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_logs', to='tracker.employee')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_logs', to='tracker.item')),
                ('logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
    ]
