# Generated by Django 5.2.16 on 2026-07-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagelog',
            name='logged_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
