# Generated by Django 5.2.16 on 2026-07-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_usagelog_logged_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='bulk_issue_cooldown_days',
            field=models.PositiveIntegerField(default=30, help_text='Number of days Bulk Issue button remains disabled after execution to prevent duplicate periodic allotment'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='last_bulk_issue_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last bulk periodic allotment execution', null=True),
        ),
    ]
