# Generated by Django 5.2.16 on 2026-08-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_appsettings_bulk_issue_cooldown_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload unique image for this equipment item', null=True, upload_to='item_images/'),
        ),
    ]
